name: GitHub Actions Lab
run-name: ${{ github.actor }} is testing out GitHub Actions
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check Environment
        run: |
          echo "$(uname -a)"
          echo "--------------------"
          cat /etc/os-release
          echo "--------------------"
          df -hT
          echo "--------------------"
          sudo rm -rf /usr/share/dotnet
          echo "--------------------"
          df -hT
          sudo rm -rf /usr/local/lib/android
          echo "After /usr/local/lib/android removed:"
          df -hT
          echo "$AGENT_TOOLSDIRECTORY"
          sudo rm -rf /usr/share/swift
          echo "After /usr/share/swift removed:"
          df -hT

