name: GitHub Actions Lab
run-name: ${{ github.actor }} is testing out GitHub Actions
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check Environment
        run: |
          echo "$(uname -a)"
          echo "--------------------"
          cat /etc/os-release
          echo "--------------------"
          df -hT
